//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuickfloraPrinting.QFPrint {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://secure.quickflora.com/", ConfigurationName="QFPrint.ServiceSoap")]
    public interface ServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/CheckPOSPaidOutPrintRequestststatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckPOSPaidOutPrintRequestststatus(string CompanyID, string DivisionID, string DepartmentID, string TerminalName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/CheckPOSPaidOutPrintRequestPrinting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable CheckPOSPaidOutPrintRequestPrinting(string CompanyID, string DivisionID, string DepartmentID, string TerminalName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/GETPOSPaidOutPrintRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GETPOSPaidOutPrintRequest(string CompanyID, string DivisionID, string DepartmentID, string PaidOutId, string ShiftID, string TerminalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/UpdatePOSPaidOutPrintRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdatePOSPaidOutPrintRequest(string CompanyID, string DivisionID, string DepartmentID, int slno);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/CheckPOSReturnOrderPrintRequeststatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckPOSReturnOrderPrintRequeststatus(string CompanyID, string DivisionID, string DepartmentID, string TerminalName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/CheckPOSReturnOrderPrintRequestPrinting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable CheckPOSReturnOrderPrintRequestPrinting(string CompanyID, string DivisionID, string DepartmentID, string TerminalName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/GETPOSReturnOrderPrintRequestForPrinting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GETPOSReturnOrderPrintRequestForPrinting(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber, string ShiftID, string TerminalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/UpdatePOSReturnOrderPrintRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdatePOSReturnOrderPrintRequest(string CompanyID, string DivisionID, string DepartmentID, int slno);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/CheckPOSShiftForPrintingstatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckPOSShiftForPrintingstatus(string CompanyID, string DivisionID, string DepartmentID, string TerminalName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/CheckPOSShiftForPrinting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable CheckPOSShiftForPrinting(string CompanyID, string DivisionID, string DepartmentID, string TerminalName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/GETPOSShiftForPrinting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GETPOSShiftForPrinting(string CompanyID, string DivisionID, string DepartmentID, string ShiftID, string TerminalId);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/UpdatePOSShiftForPrinting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdatePOSShiftForPrinting(string CompanyID, string DivisionID, string DepartmentID, int slno);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/CheckPOSForPrintingstatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckPOSForPrintingstatus(string CompanyID, string DivisionID, string DepartmentID, string TerminalName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/CheckPOSForPrinting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable CheckPOSForPrinting(string CompanyID, string DivisionID, string DepartmentID, string TerminalName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/UpdatePOSForPrinting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdatePOSForPrinting(string CompanyID, string DivisionID, string DepartmentID, int slno);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/PaymentDetailsForRefund", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable PaymentDetailsForRefund(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/GetRefundOrderDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetRefundOrderDetails(string CompanyID, string DivisionID, string DepartmentID, string TerminalName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/GetRefundOrderPaymentDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetRefundOrderPaymentDetails(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/CheckOrderForPaymentRefund", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckOrderForPaymentRefund(string CompanyID, string DivisionID, string DepartmentID, string TerminalName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/UpdateOrderDetailsPaymentrefund", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateOrderDetailsPaymentrefund(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber, string CMDStatus, string ApprovalNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/PaymentGatewayTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PaymentGatewayTransaction(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber, string InLineNumber, string ProcessData, string ACQRefData, string InvoiceNo, string Response_RefNo, string AuthCode, string TextResponse, string CmdStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/PaymentGatewayTransactionRefund", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PaymentGatewayTransactionRefund(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber, string InLineNumber, string ProcessData, string ACQRefData, string InvoiceNo, string Response_RefNo, string AuthCode, string TextResponse, string CmdStatus, string ProcessType);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/CheckConnection", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.DateTime CheckConnection();
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/CheckOrderForPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool CheckOrderForPayment(string CompanyID, string DivisionID, string DepartmentID, string TerminalName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/GetOrderDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetOrderDetails(string CompanyID, string DivisionID, string DepartmentID, string TerminalName);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/UpdateOrderDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateOrderDetails(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber, string CMDStatus, string ApprovalNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/UpdateOrderHeaderForPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool UpdateOrderHeaderForPayment(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/ReceiptPDFPrintData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ReceiptPDFPrintData(string CompanyID, string DivisionID, string DepartmentID, string OrdNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/ReceiptPDFPrintDataPickscreen", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ReceiptPDFPrintDataPickscreen(string CompanyID, string DivisionID, string DepartmentID, string OrdNumber, string TerminalName, string slno);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://secure.quickflora.com/ReceiptPrintData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReceiptPrintData(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : QuickfloraPrinting.QFPrint.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<QuickfloraPrinting.QFPrint.ServiceSoap>, QuickfloraPrinting.QFPrint.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CheckPOSPaidOutPrintRequestststatus(string CompanyID, string DivisionID, string DepartmentID, string TerminalName) {
            return base.Channel.CheckPOSPaidOutPrintRequestststatus(CompanyID, DivisionID, DepartmentID, TerminalName);
        }
        
        public System.Data.DataTable CheckPOSPaidOutPrintRequestPrinting(string CompanyID, string DivisionID, string DepartmentID, string TerminalName) {
            return base.Channel.CheckPOSPaidOutPrintRequestPrinting(CompanyID, DivisionID, DepartmentID, TerminalName);
        }
        
        public string GETPOSPaidOutPrintRequest(string CompanyID, string DivisionID, string DepartmentID, string PaidOutId, string ShiftID, string TerminalId) {
            return base.Channel.GETPOSPaidOutPrintRequest(CompanyID, DivisionID, DepartmentID, PaidOutId, ShiftID, TerminalId);
        }
        
        public bool UpdatePOSPaidOutPrintRequest(string CompanyID, string DivisionID, string DepartmentID, int slno) {
            return base.Channel.UpdatePOSPaidOutPrintRequest(CompanyID, DivisionID, DepartmentID, slno);
        }
        
        public bool CheckPOSReturnOrderPrintRequeststatus(string CompanyID, string DivisionID, string DepartmentID, string TerminalName) {
            return base.Channel.CheckPOSReturnOrderPrintRequeststatus(CompanyID, DivisionID, DepartmentID, TerminalName);
        }
        
        public System.Data.DataTable CheckPOSReturnOrderPrintRequestPrinting(string CompanyID, string DivisionID, string DepartmentID, string TerminalName) {
            return base.Channel.CheckPOSReturnOrderPrintRequestPrinting(CompanyID, DivisionID, DepartmentID, TerminalName);
        }
        
        public string GETPOSReturnOrderPrintRequestForPrinting(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber, string ShiftID, string TerminalId) {
            return base.Channel.GETPOSReturnOrderPrintRequestForPrinting(CompanyID, DivisionID, DepartmentID, OrderNumber, ShiftID, TerminalId);
        }
        
        public bool UpdatePOSReturnOrderPrintRequest(string CompanyID, string DivisionID, string DepartmentID, int slno) {
            return base.Channel.UpdatePOSReturnOrderPrintRequest(CompanyID, DivisionID, DepartmentID, slno);
        }
        
        public bool CheckPOSShiftForPrintingstatus(string CompanyID, string DivisionID, string DepartmentID, string TerminalName) {
            return base.Channel.CheckPOSShiftForPrintingstatus(CompanyID, DivisionID, DepartmentID, TerminalName);
        }
        
        public System.Data.DataTable CheckPOSShiftForPrinting(string CompanyID, string DivisionID, string DepartmentID, string TerminalName) {
            return base.Channel.CheckPOSShiftForPrinting(CompanyID, DivisionID, DepartmentID, TerminalName);
        }
        
        public string GETPOSShiftForPrinting(string CompanyID, string DivisionID, string DepartmentID, string ShiftID, string TerminalId) {
            return base.Channel.GETPOSShiftForPrinting(CompanyID, DivisionID, DepartmentID, ShiftID, TerminalId);
        }
        
        public bool UpdatePOSShiftForPrinting(string CompanyID, string DivisionID, string DepartmentID, int slno) {
            return base.Channel.UpdatePOSShiftForPrinting(CompanyID, DivisionID, DepartmentID, slno);
        }
        
        public bool CheckPOSForPrintingstatus(string CompanyID, string DivisionID, string DepartmentID, string TerminalName) {
            return base.Channel.CheckPOSForPrintingstatus(CompanyID, DivisionID, DepartmentID, TerminalName);
        }
        
        public System.Data.DataTable CheckPOSForPrinting(string CompanyID, string DivisionID, string DepartmentID, string TerminalName) {
            return base.Channel.CheckPOSForPrinting(CompanyID, DivisionID, DepartmentID, TerminalName);
        }
        
        public bool UpdatePOSForPrinting(string CompanyID, string DivisionID, string DepartmentID, int slno) {
            return base.Channel.UpdatePOSForPrinting(CompanyID, DivisionID, DepartmentID, slno);
        }
        
        public System.Data.DataTable PaymentDetailsForRefund(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber) {
            return base.Channel.PaymentDetailsForRefund(CompanyID, DivisionID, DepartmentID, OrderNumber);
        }
        
        public System.Data.DataTable GetRefundOrderDetails(string CompanyID, string DivisionID, string DepartmentID, string TerminalName) {
            return base.Channel.GetRefundOrderDetails(CompanyID, DivisionID, DepartmentID, TerminalName);
        }
        
        public System.Data.DataTable GetRefundOrderPaymentDetails(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber) {
            return base.Channel.GetRefundOrderPaymentDetails(CompanyID, DivisionID, DepartmentID, OrderNumber);
        }
        
        public bool CheckOrderForPaymentRefund(string CompanyID, string DivisionID, string DepartmentID, string TerminalName) {
            return base.Channel.CheckOrderForPaymentRefund(CompanyID, DivisionID, DepartmentID, TerminalName);
        }
        
        public bool UpdateOrderDetailsPaymentrefund(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber, string CMDStatus, string ApprovalNo) {
            return base.Channel.UpdateOrderDetailsPaymentrefund(CompanyID, DivisionID, DepartmentID, OrderNumber, CMDStatus, ApprovalNo);
        }
        
        public string PaymentGatewayTransaction(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber, string InLineNumber, string ProcessData, string ACQRefData, string InvoiceNo, string Response_RefNo, string AuthCode, string TextResponse, string CmdStatus) {
            return base.Channel.PaymentGatewayTransaction(CompanyID, DivisionID, DepartmentID, OrderNumber, InLineNumber, ProcessData, ACQRefData, InvoiceNo, Response_RefNo, AuthCode, TextResponse, CmdStatus);
        }
        
        public string PaymentGatewayTransactionRefund(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber, string InLineNumber, string ProcessData, string ACQRefData, string InvoiceNo, string Response_RefNo, string AuthCode, string TextResponse, string CmdStatus, string ProcessType) {
            return base.Channel.PaymentGatewayTransactionRefund(CompanyID, DivisionID, DepartmentID, OrderNumber, InLineNumber, ProcessData, ACQRefData, InvoiceNo, Response_RefNo, AuthCode, TextResponse, CmdStatus, ProcessType);
        }
        
        public System.DateTime CheckConnection() {
            return base.Channel.CheckConnection();
        }
        
        public bool CheckOrderForPayment(string CompanyID, string DivisionID, string DepartmentID, string TerminalName) {
            return base.Channel.CheckOrderForPayment(CompanyID, DivisionID, DepartmentID, TerminalName);
        }
        
        public System.Data.DataTable GetOrderDetails(string CompanyID, string DivisionID, string DepartmentID, string TerminalName) {
            return base.Channel.GetOrderDetails(CompanyID, DivisionID, DepartmentID, TerminalName);
        }
        
        public bool UpdateOrderDetails(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber, string CMDStatus, string ApprovalNo) {
            return base.Channel.UpdateOrderDetails(CompanyID, DivisionID, DepartmentID, OrderNumber, CMDStatus, ApprovalNo);
        }
        
        public bool UpdateOrderHeaderForPayment(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber) {
            return base.Channel.UpdateOrderHeaderForPayment(CompanyID, DivisionID, DepartmentID, OrderNumber);
        }
        
        public System.Data.DataTable ReceiptPDFPrintData(string CompanyID, string DivisionID, string DepartmentID, string OrdNumber) {
            return base.Channel.ReceiptPDFPrintData(CompanyID, DivisionID, DepartmentID, OrdNumber);
        }
        
        public System.Data.DataTable ReceiptPDFPrintDataPickscreen(string CompanyID, string DivisionID, string DepartmentID, string OrdNumber, string TerminalName, string slno) {
            return base.Channel.ReceiptPDFPrintDataPickscreen(CompanyID, DivisionID, DepartmentID, OrdNumber, TerminalName, slno);
        }
        
        public string ReceiptPrintData(string CompanyID, string DivisionID, string DepartmentID, string OrderNumber) {
            return base.Channel.ReceiptPrintData(CompanyID, DivisionID, DepartmentID, OrderNumber);
        }
    }
}
