//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace QuickfloraPrinting.QFPrintService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="QFPrintServiceSoap", Namespace="https://secure.quickflora.com/")]
    public partial class QFPrintService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InsertMacRequestOperationCompleted;
        
        private System.Threading.SendOrPostCallback InsertErrorDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback PingPOSForPrintingOperationCompleted;
        
        private System.Threading.SendOrPostCallback CheckPOSForPrintingOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateReadPOSForPrintingOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdatePOSForPrintingOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QFPrintService() {
            this.Url = global::QuickfloraPrinting.Properties.Settings.Default.QuickfloraPrinting_QFPrintService_QFPrintService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InsertMacRequestCompletedEventHandler InsertMacRequestCompleted;
        
        /// <remarks/>
        public event InsertErrorDetailsCompletedEventHandler InsertErrorDetailsCompleted;
        
        /// <remarks/>
        public event PingPOSForPrintingCompletedEventHandler PingPOSForPrintingCompleted;
        
        /// <remarks/>
        public event CheckPOSForPrintingCompletedEventHandler CheckPOSForPrintingCompleted;
        
        /// <remarks/>
        public event UpdateReadPOSForPrintingCompletedEventHandler UpdateReadPOSForPrintingCompleted;
        
        /// <remarks/>
        public event UpdatePOSForPrintingCompletedEventHandler UpdatePOSForPrintingCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://secure.quickflora.com/InsertMacRequest", RequestNamespace="https://secure.quickflora.com/", ResponseNamespace="https://secure.quickflora.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool InsertMacRequest(string Token, string MAC) {
            object[] results = this.Invoke("InsertMacRequest", new object[] {
                        Token,
                        MAC});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void InsertMacRequestAsync(string Token, string MAC) {
            this.InsertMacRequestAsync(Token, MAC, null);
        }
        
        /// <remarks/>
        public void InsertMacRequestAsync(string Token, string MAC, object userState) {
            if ((this.InsertMacRequestOperationCompleted == null)) {
                this.InsertMacRequestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertMacRequestOperationCompleted);
            }
            this.InvokeAsync("InsertMacRequest", new object[] {
                        Token,
                        MAC}, this.InsertMacRequestOperationCompleted, userState);
        }
        
        private void OnInsertMacRequestOperationCompleted(object arg) {
            if ((this.InsertMacRequestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertMacRequestCompleted(this, new InsertMacRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://secure.quickflora.com/InsertErrorDetails", RequestNamespace="https://secure.quickflora.com/", ResponseNamespace="https://secure.quickflora.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InsertErrorDetails(string CompanyID, string DivisionID, string DepartmentID, string TerminalName, string Order, string ErrorsDetails, string Details) {
            object[] results = this.Invoke("InsertErrorDetails", new object[] {
                        CompanyID,
                        DivisionID,
                        DepartmentID,
                        TerminalName,
                        Order,
                        ErrorsDetails,
                        Details});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InsertErrorDetailsAsync(string CompanyID, string DivisionID, string DepartmentID, string TerminalName, string Order, string ErrorsDetails, string Details) {
            this.InsertErrorDetailsAsync(CompanyID, DivisionID, DepartmentID, TerminalName, Order, ErrorsDetails, Details, null);
        }
        
        /// <remarks/>
        public void InsertErrorDetailsAsync(string CompanyID, string DivisionID, string DepartmentID, string TerminalName, string Order, string ErrorsDetails, string Details, object userState) {
            if ((this.InsertErrorDetailsOperationCompleted == null)) {
                this.InsertErrorDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInsertErrorDetailsOperationCompleted);
            }
            this.InvokeAsync("InsertErrorDetails", new object[] {
                        CompanyID,
                        DivisionID,
                        DepartmentID,
                        TerminalName,
                        Order,
                        ErrorsDetails,
                        Details}, this.InsertErrorDetailsOperationCompleted, userState);
        }
        
        private void OnInsertErrorDetailsOperationCompleted(object arg) {
            if ((this.InsertErrorDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InsertErrorDetailsCompleted(this, new InsertErrorDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://secure.quickflora.com/PingPOSForPrinting", RequestNamespace="https://secure.quickflora.com/", ResponseNamespace="https://secure.quickflora.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool PingPOSForPrinting(string CompanyID, string DivisionID, string DepartmentID, string TerminalName) {
            object[] results = this.Invoke("PingPOSForPrinting", new object[] {
                        CompanyID,
                        DivisionID,
                        DepartmentID,
                        TerminalName});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void PingPOSForPrintingAsync(string CompanyID, string DivisionID, string DepartmentID, string TerminalName) {
            this.PingPOSForPrintingAsync(CompanyID, DivisionID, DepartmentID, TerminalName, null);
        }
        
        /// <remarks/>
        public void PingPOSForPrintingAsync(string CompanyID, string DivisionID, string DepartmentID, string TerminalName, object userState) {
            if ((this.PingPOSForPrintingOperationCompleted == null)) {
                this.PingPOSForPrintingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingPOSForPrintingOperationCompleted);
            }
            this.InvokeAsync("PingPOSForPrinting", new object[] {
                        CompanyID,
                        DivisionID,
                        DepartmentID,
                        TerminalName}, this.PingPOSForPrintingOperationCompleted, userState);
        }
        
        private void OnPingPOSForPrintingOperationCompleted(object arg) {
            if ((this.PingPOSForPrintingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PingPOSForPrintingCompleted(this, new PingPOSForPrintingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://secure.quickflora.com/CheckPOSForPrinting", RequestNamespace="https://secure.quickflora.com/", ResponseNamespace="https://secure.quickflora.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable CheckPOSForPrinting(string CompanyID, string DivisionID, string DepartmentID, string TerminalName) {
            object[] results = this.Invoke("CheckPOSForPrinting", new object[] {
                        CompanyID,
                        DivisionID,
                        DepartmentID,
                        TerminalName});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CheckPOSForPrintingAsync(string CompanyID, string DivisionID, string DepartmentID, string TerminalName) {
            this.CheckPOSForPrintingAsync(CompanyID, DivisionID, DepartmentID, TerminalName, null);
        }
        
        /// <remarks/>
        public void CheckPOSForPrintingAsync(string CompanyID, string DivisionID, string DepartmentID, string TerminalName, object userState) {
            if ((this.CheckPOSForPrintingOperationCompleted == null)) {
                this.CheckPOSForPrintingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCheckPOSForPrintingOperationCompleted);
            }
            this.InvokeAsync("CheckPOSForPrinting", new object[] {
                        CompanyID,
                        DivisionID,
                        DepartmentID,
                        TerminalName}, this.CheckPOSForPrintingOperationCompleted, userState);
        }
        
        private void OnCheckPOSForPrintingOperationCompleted(object arg) {
            if ((this.CheckPOSForPrintingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CheckPOSForPrintingCompleted(this, new CheckPOSForPrintingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://secure.quickflora.com/UpdateReadPOSForPrinting", RequestNamespace="https://secure.quickflora.com/", ResponseNamespace="https://secure.quickflora.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdateReadPOSForPrinting(string CompanyID, string DivisionID, string DepartmentID, int slno) {
            object[] results = this.Invoke("UpdateReadPOSForPrinting", new object[] {
                        CompanyID,
                        DivisionID,
                        DepartmentID,
                        slno});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateReadPOSForPrintingAsync(string CompanyID, string DivisionID, string DepartmentID, int slno) {
            this.UpdateReadPOSForPrintingAsync(CompanyID, DivisionID, DepartmentID, slno, null);
        }
        
        /// <remarks/>
        public void UpdateReadPOSForPrintingAsync(string CompanyID, string DivisionID, string DepartmentID, int slno, object userState) {
            if ((this.UpdateReadPOSForPrintingOperationCompleted == null)) {
                this.UpdateReadPOSForPrintingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateReadPOSForPrintingOperationCompleted);
            }
            this.InvokeAsync("UpdateReadPOSForPrinting", new object[] {
                        CompanyID,
                        DivisionID,
                        DepartmentID,
                        slno}, this.UpdateReadPOSForPrintingOperationCompleted, userState);
        }
        
        private void OnUpdateReadPOSForPrintingOperationCompleted(object arg) {
            if ((this.UpdateReadPOSForPrintingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateReadPOSForPrintingCompleted(this, new UpdateReadPOSForPrintingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://secure.quickflora.com/UpdatePOSForPrinting", RequestNamespace="https://secure.quickflora.com/", ResponseNamespace="https://secure.quickflora.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UpdatePOSForPrinting(string CompanyID, string DivisionID, string DepartmentID, int slno) {
            object[] results = this.Invoke("UpdatePOSForPrinting", new object[] {
                        CompanyID,
                        DivisionID,
                        DepartmentID,
                        slno});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UpdatePOSForPrintingAsync(string CompanyID, string DivisionID, string DepartmentID, int slno) {
            this.UpdatePOSForPrintingAsync(CompanyID, DivisionID, DepartmentID, slno, null);
        }
        
        /// <remarks/>
        public void UpdatePOSForPrintingAsync(string CompanyID, string DivisionID, string DepartmentID, int slno, object userState) {
            if ((this.UpdatePOSForPrintingOperationCompleted == null)) {
                this.UpdatePOSForPrintingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdatePOSForPrintingOperationCompleted);
            }
            this.InvokeAsync("UpdatePOSForPrinting", new object[] {
                        CompanyID,
                        DivisionID,
                        DepartmentID,
                        slno}, this.UpdatePOSForPrintingOperationCompleted, userState);
        }
        
        private void OnUpdatePOSForPrintingOperationCompleted(object arg) {
            if ((this.UpdatePOSForPrintingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdatePOSForPrintingCompleted(this, new UpdatePOSForPrintingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InsertMacRequestCompletedEventHandler(object sender, InsertMacRequestCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertMacRequestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertMacRequestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InsertErrorDetailsCompletedEventHandler(object sender, InsertErrorDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InsertErrorDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InsertErrorDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void PingPOSForPrintingCompletedEventHandler(object sender, PingPOSForPrintingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PingPOSForPrintingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PingPOSForPrintingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void CheckPOSForPrintingCompletedEventHandler(object sender, CheckPOSForPrintingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CheckPOSForPrintingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CheckPOSForPrintingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdateReadPOSForPrintingCompletedEventHandler(object sender, UpdateReadPOSForPrintingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateReadPOSForPrintingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateReadPOSForPrintingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UpdatePOSForPrintingCompletedEventHandler(object sender, UpdatePOSForPrintingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdatePOSForPrintingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdatePOSForPrintingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591